### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by mjhartley4** [mjhartley4/SEBC#2]

**Comment by mjhartley4** [comment]
check swappiness: sysctl vm.swappiness
change swappiness: sudo sysctl vm.swappiness=1
Check mount attributes: sudo parted -l

**Comment by mjhartley4** [comment]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html

**Comment by mjhartley4** [comment]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#having-ec2-create-your-key-pair

**Comment by mjhartley4** [comment]
Check the hugepage is enabled: cat /sys/kernel/mm/transparent_hugepage/enabled or grep AnonHugePages /proc/meminfo
sudo apt-get install nano
sudo nano -w /etc/rc.local
sudo su 
sudo echo never > /sys/kernel/mm/transparent_hugepage/enabled

**Comment by mjhartley4** [comment]
http://linuxcommando.blogspot.com.au/2008/07/how-to-do-reverse-dns-lookup.html

**Comment by mjhartley4** [comment]
rpm -q  wget
yum install wget

**Comment by mjhartley4** [comment]
$ wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
$ sudo rpm -ivh mysql-community-release-el7-5.noarch.rpm
$ yum update
$ sudo yum install mysql-server
$ sudo systemctl start mysqld

**Comment by mjhartley4** [comment]
wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.42.tar.gz
tar zxvf mysql-connector-java-5.1.42.tar.gz

**Comment by mjhartley4** [comment]
$ sudo mkdir -p /usr/share/java/
$ sudo cp mysql-connector-java-5.1.31/mysql-connector-java-5.1.31-bin.jar /usr/share/java/mysql-connector-java.jar

**Comment by mjhartley4** [comment]
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip install psycopg2

**Comment by mjhartley4** [comment]
wget https://archive.cloudera.com/cm5/redhat/5/x86_64/cm/cloudera-manager.repo
cp cloudera-manager.repo /etc/yum.repos.d/
yum update
sudo yum install oracle-j2skd1.7

**Comment by mjhartley4** [comment]
sudo yum install cloudera-manager-daemons cloudera-manager-server

**Comment by mjhartley4** [comment]
https://www.cloudera.com/documentation/enterprise/latest/topics/cm_ig_mysql.html

**Comment by mjhartley4** [comment]
Have set up the nodes then loaded cloudera manager. Having difficulty connecting to 2 of 5 nodes.
5 hosts scanned, 2 running SSH. Checked firewalls iptables, dont seem to be running. trying to disable selinux - sudo nano /etc/selinux/config. change line to selinux disabled

**Comment by mjhartley4** [comment]
had to open all the ports on the TCP ports in order to communicate. Now installing

**Comment by mjhartley4** [comment]
installation stops at activating the 5th of 5 parcels. Everything else seems to work.. the server is the main node

**Comment by mfernest** [comment]
We can take a look at this in the morning.

**Comment by mjhartley4** [comment]
Started from scratch - seems to now be working, almost done with the install

**Comment by mjhartley4** [comment]
cluster set up successfully!!

**Comment by mjhartley4** [comment]
![image](https://cloud.githubusercontent.com/assets/28218860/25688614/0c9865fe-30c4-11e7-9fd9-0be0993f9730.png)

**Comment by mfernest** [comment]
I am glad to see all the progress posted here. Unfortunately I don't see any of it in the `labs/` folder...
